services:
    nginx:
        image: nginx:latest
        stop_signal: SIGINT
        ports:
            - "80:80"
        volumes:
            - "./.docker/nginx/local.conf:/etc/nginx/conf.d/local.conf"
            - "./.docker/nginx/logs/:/var/log/nginx/"
            - "./:/var/www/exchangerates.local/"
        links:
            - php-fpm

    php-fpm:
        build: ./.docker/php-fpm
        volumes:
            - "./.docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/40-local.ini"
            - "./.docker/php-fpm/fpm.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./.docker/php-fpm/logs/:/var/log/"
            - "./:/var/www/exchangerates.local/"
        links:
            - mysql

    mysql:
        image: mysql:8
        hostname: exchangerates.local
        ports:
            - "3306:3306"
        volumes:
            - "./.docker/mysql/logs/:/var/log/mysql/"
            - "./.docker/mysql/data/:/var/lib/mysql/"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: exchangerates
            MYSQL_DATABASE: exchangerates
            MYSQL_USER: exchange_user
            MYSQL_PASSWORD: exchange_Pass
